services:
  postgres:
    image: postgres:16.4
    container_name: stylazar_pg
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: stylazar_rds
    restart: always
    env_file: .env
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  # mongo:
  mongo:
    image: mongo:8.0
    container_name: stylazar_mongo
    ports:
      - ${MONGO_PORT}:27017
    restart: always
    logging:
      options:
        max-size: 1g
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db 

volumes:
  pgdata:
  redis_data:
  mongo_data:
