[project]
name = "stylazar_blog_backend"
version = "0.1.0"
description = "Contains the app's backend - API, storage"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcrypt>=4.2.0",
    "fastapi[standard]>=0.115.2",
    "psycopg>=3.2.3",
    "sqlmodel>=0.0.22",
]
